### PR TITLE
idk wtf this code means but i found it in the...

### PR DESCRIPTION
**Pull request by DiamondCoder1000**
idk wtf this code means but i found it in the URCL explorer examples so...

### CODE REVIEW

**Comment by em3rald1** [comment]
assert is kinda useless right now, as u can literally make it in your code, but that bressy algorithm is useful, so i will use it

**Comment by em3rald1** [comment]
audio lib is kinda useless right now too, as it would have use only if you're building an entire OS or game, but stdlib is not a game nor an OS, so i wont add it

**Review by em3rald1 — COMMENTED** [review]
bro u forgot ret after cal .printf smh

**Comment by DiamondCoder1000** [comment]
Oh lol

**Comment by DiamondCoder1000** [comment]
> audio lib is kinda useless right now too, as it would have use only if you're building an entire OS or game, but stdlib is not a game nor an OS, so i wont add it

Well, this IS a stdlib for urcl, so...

**Comment by DiamondCoder1000** [comment]
> assert is kinda useless right now, as u can literally make it in your code, but that bressy algorithm is useful, so i will use it

Yeah but what if u gotta do like 50 thousand checks in ur code? Manually typing that would be a pain in the ass tbh

**Comment by em3rald1** [comment]
fr, imma merge, 1 sec

**Pull request merged**
